### ISSUE TITLE
BRAOfficeDocument object is getting data nil while we fetch .xlsx file from project directory.

### ISSUE THREAD

**Issue by nvnsn386** [renebigot/XlsxReaderWriter#23]
NSString *documentPath = [[NSBundle mainBundle] pathForResource:@"DemoWorkBook" ofType:@"xlsx"];
    BRAOfficeDocumentPackage *spreadsheet = [BRAOfficeDocumentPackage open:documentPath];
I've DemoWorkBook.xlsx in Document directory. when it create BRAOfficeDocumentPackage object It shows BRAOfficeDocument  object in worksheet property,  but in this object all data showing nil.
 I need sheets data. Please help me out...

https://cloud.githubusercontent.com/assets/8234036/13868907/e7eb2508-ecf3-11e5-9ca6-a268ca88ae25.png

**Comment by renebigot** [comment]
If DemoWorkBook is in Document directory (iTunes documents folder ?), this can't work.
Your code assume that DemoWorkBook.xlsx is a resource of you application, not a resource imported by user.
You have to give the full path to your workbook.

`NSString *documentPath = [[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) lastObject] stringByAppendingPathComponent:@"workbookCopy.xlsx"];`

**Comment by renebigot** [comment]
Or, for swift : 

`var documentPath: String = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, true).lastObject().stringByAppendingPathComponent("DemoWorkBook.xlsx")`

**Comment by nvnsn386** [comment]
I was doing minor mistake. Now It's working. Thanx

**Comment by puka9x** [comment]
I'm a having problems

NSString *documentPathOff = [[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) lastObject] stringByAppendingPathComponent:@"DungDTchecked.xlsx"];
    
BRAOfficeDocumentPackage *spreadsheet = [BRAOfficeDocumentPackage open:documentPathOff];

Error: 
Error while loading content of file [Content_Types].xml.

Error Domain=NSCocoaErrorDomain Code=260 "The file “[Content_Types].xml” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/trivm/Library/Developer/CoreSimulator/Devices/5CC7E12F-01AD-4BD8-9D73-78EC185DF228/data/Containers/Data/Application/76E94945-C6FC-4A8A-AA05-152F45AE46F2/Library/Caches/fr.brae.spreadsheetdocument/DungDTchecked.xlsx/[Content_Types].xml, NSUnderlyingError=0x7fa861423940 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2016-12-19 17:16:26.798 MoKet[7996:196880] Error while loading content of file .rels.

Error Domain=NSCocoaErrorDomain Code=260 "The file “.rels” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/trivm/Library/Developer/CoreSimulator/Devices/5CC7E12F-01AD-4BD8-9D73-78EC185DF228/data/Containers/Data/Application/76E94945-C6FC-4A8A-AA05-152F45AE46F2/Library/Caches/fr.brae.spreadsheetdocument/DungDTchecked.xlsx/_rels/.rels, NSUnderlyingError=0x7fa861630f80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

PLEASE HELP ME.
